### ISSUE TITLE
Rename repository to Interaction.Aurelia

### ISSUE THREAD

**Issue by einari** [dolittle-boilerplates/Interaction.Web.JS.Aurelia#5]
The goal is to not be dependant on CSharp, and its not an entire bounded context - its just the interaction part of it.

**Comment by woksin** [comment]
Same as #4, just need to remove "BoundedContext" as well,  @einari

**Comment by einari** [comment]
👍  Didn't look at the existing issues, updated #4 - sorry about that.. Closing this.
